# 서버 포트 설정
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# database 연동 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: c##yoasobi
    password: tiger
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create